name: Build Project, Create Release and Deploy to Coolify

on:
  workflow_call:

jobs:
  mirror-repo:
    uses: ./.github/workflows/mirror.yaml
    secrets: inherit

  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_next_version.outputs.version }}
      hasNextVersion: ${{ steps.get_next_version.outputs.hasNextVersion }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Get Next Version
        id: get_next_version
        uses: thenativeweb/get-next-version@main

  call-build:
    needs: get-version
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.get-version.outputs.version }}

  call-release:
    needs: get-version
    if: ${{ needs.get-version.outputs.hasNextVersion == 'true' }}
    uses: ./.github/workflows/create-release.yaml
    with:
      version: ${{ needs.get-version.outputs.version }}
          
  deploy-to-coolify:
    uses: ./.github/workflows/deploy-to-coolify.yaml
    secrets: inherit