name: Create Tag and Release

on:
  workflow_call:
    inputs:
      version:
        description: 'Die Version, die als Tag und Release verwendet wird'
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set Git Configs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Tag
        run: |
          git tag -a ${{ inputs.version }} -m ""
          git push origin ${{ inputs.version }}

      - name: Create New Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_PAT }}
          tag: ${{ inputs.version }}
          body: "- Docker image: https://$GITHUB_CONTAINER_REGISTRY:${{ inputs.version }}"
