name: build and create release

on:
  push:
    branches:
      - main

jobs:
  build-and-create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

  mirror-repo:
        uses: ./.github/workflows/common/mirror.yaml
        secrets: inherit