name: Find Dockerfiles

on:
    workflow_call:
        
jobs:
  find-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.get_files.outputs.dockerfiles }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Find all Dockerfiles
        id: get_files
        run: |
          dockerfiles=$(./scripts/find-dockerfiles.sh)
          echo "dockerfiles=$dockerfiles" >> $GITHUB_OUTPUT
