name: Build Project

on:
  workflow_call:
    # inputs:




jobs:
  build-and-create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Mirror Repo

      - name: Convert repository name to lowercase
        id: lowercase_repo
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push Docker Image
        run: |
          docker build ./pomodoro-timer -t ghcr.io/${{ env.REPO_NAME }}:dev 
          docker push ghcr.io/${{ env.REPO_NAME }}:dev

      - name: Deploy to Coolify
        run: | 
           curl --request GET '${{ secrets.DEV_COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'