name: Develope Project

on:
  workflow_call:
    inputs:
      mirror-repo:
        required: false
        type: boolean
        default: false

jobs:
  mirror-repo:
    uses: ./.github/workflows/mirror.yaml
    secrets: inherit  
    
