name: Find Dockerfiles

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  find-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.set-matrix.outputs.dockerfiles }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find all Dockerfiles
        id: set-matrix
        run: |
          # Suche nach allen Dateien, die mit "Dockerfile" beginnen
          files=$(find . -type f -name 'Dockerfile*')
          echo "Gefundene Dockerfiles:"
          echo "$files"
          # Erstelle ein JSON-Array aus den gefundenen Dateien
          files_json=$(echo "$files" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "dockerfiles=$files_json" >> $GITHUB_OUTPUT