name: Main Pipeline

on:
  workflow_call:

jobs:
  mirror-repo:
    uses: ./.github/workflows/mirror-to-other-repos.yaml
    secrets: inherit
  get_version:
      # This job only runs if the pushed branch is "main"
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.get_version.outputs.version }}
        hasNextVersion: ${{ steps.get_version.outputs.hasNextVersion }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            token: ${{ secrets.GH_PAT }}
        - name: Get Next Version
          id: get_version
          uses: thenativeweb/get-next-version@main
  build-publish:
    needs: get_version
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      version: ${{ needs.get_version.outputs.version }}
    secrets: inherit
  release_and_tag:
    if: ${{ needs.get_version.outputs.hasNextVersion == 'true' }}
    needs: get_version
    uses: ./.github/workflows/create-tag-and-release.yaml
    with:
      version: ${{ needs.get_version.outputs.version }}
    secrets: inherit
  deploy-prod:
    # This job only runs if the pushed branch is "main"
    if: ${{ needs.get_version.outputs.hasNextVersion  == 'true' }}
    needs: [get_version]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Coolify Production
        run: |
          echo "Running production scripts..."
          bash ./scripts/bash/deploy-to-coolify.sh prod
        env:
          PROD_COOLIFY_WEBHOOK: ${{ secrets.PROD_COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}

  deploy-dev:
    # This job runs for any branch that is not "main"
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Coolify Development
        run: |
          echo "Running development scripts..."
          bash ./scripts/bash/deploy-to-coolify.sh dev
        env:
          DEV_COOLIFY_WEBHOOK: ${{ secrets.DEV_COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
