name: Main Pipeline

on:
  workflow_call:

jobs:
  mirror-repo:
    uses: ./.github/workflows/mirror-to-other-repos.yaml
    secrets: inherit
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      hasNextVersion: ${{ steps.get_version.outputs.hasNextVersion }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Get Next Version or Set Default
        id: get_version
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            VERSION=$(thenativeweb/get-next-version) 
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "hasNextVersion=true" >> $GITHUB_OUTPUT
          else
            echo "version=dev-version" >> $GITHUB_OUTPUT
            echo "hasNextVersion=false" >> $GITHUB_OUTPUT
          fi
  build-and-publish:
    needs: get_version
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      version: ${{ needs.get_version.outputs.version }}
    secrets: inherit
  release_and_tag:
    if: ${{ needs.get_version.outputs.hasNextVersion == 'true' }}
    needs: get_version
    uses: ./.github/workflows/create-tag-and-release.yaml
    with:
      version: ${{ needs.get_version.outputs.version }}
    secrets: inherit
  deploy-to-coolify:
    needs: build-and-publish
    uses: ./.github/workflows/deploy-to-coolify.yaml
    with:
      branch: ${{ github.ref_name }}
    secrets: inherit
