name: Mirror Repos

on:
  workflow_call:

env:
  CODEBERG_REPO: ssh://git@codeberg.org/${{ github.repository }}.git
  GITLAB_REPO: ssh://git@gitlab.com/${{ github.repository }}.git
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}


jobs:
  mirror-codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Push to Codeberg.org
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        uses: yesolutions/mirror-action@master
        with:
           REMOTE:  ${{ env.CODEBERG_REPO }}
           GIT_SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
           GIT_SSH_NO_VERIFY_HOST: "true"
  mirror-gitlab:
    runs-on: ubuntu-latest
    steps:
        - name: Clone repository
          if: ${{ env.SSH_PRIVATE_KEY != ''}} 
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Push to Gitlab.com
          if: ${{ env.SSH_PRIVATE_KEY != ''}}
          uses: yesolutions/mirror-action@master
          with:
              REMOTE: ${{env.GITLAB_REPO}}
              GIT_SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
              GIT_SSH_NO_VERIFY_HOST: "true"