name: Mirror Repos

on:
  workflow_call:

env:
  CODEBERG_REPO: ssh://git@codeberg.org/TheKing6488/${{ github.repository }}.git
  GITLAB_REPO: ssh://git@gitlab.com/TheKing6488/${{ github.repository }}.git


jobs:
  check-input:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Codeberg Repo
        run: |
            echo ${{ env.CODEBERG_REPO }}
      - name: Gitlab Repo
        run: |
            echo ${{env.GITLAB_REPO}}

      - name: Push to Codeberg.org
        uses: yesolutions/mirror-action@master
        with:
           REMOTE:  ${{ env.CODEBERG_REPO }}
           GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           GIT_SSH_NO_VERIFY_HOST: "true"

      - name: Push to Gitlab.com
        uses: yesolutions/mirror-action@master
        with:
            REMOTE: ${{env.GITLAB_REPO}}
            GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
