name: Mirror Repos

on:
  workflow_dispatch:

env:
  GITLAB_REPO: ssh://git@gitlab.com:TheKing6488/$GITHUB_REPOSITORY.git
  CODEBERG_REPO: ssh://git@codeberg.org/TheKing6488/$GITHUB_REPOSITORY.git

jobs:
  check-input:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Codeberg.org
        uses: yesolutions/mirror-action@master
        with:
           REMOTE: 'env.CODEBERG_REPO'
           GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           GIT_SSH_NO_VERIFY_HOST: "true"

      - name: Push to Gitlab.com
        uses: yesolutions/mirror-action@master
        with:
            REMOTE: 'env.GITLAB_REPO'
            GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
